/*
 * This file is generated by jOOQ.
 */
package com.khoa.play.jooq;


import com.khoa.play.jooq.tables.Author;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = com.khoa.play.jooq.tables.Author.AUTHOR;
}
