/*
 * This file is generated by jOOQ.
 */
package com.khoa.play.jooq;


import com.khoa.play.jooq.tables.Author;
import com.khoa.play.jooq.tables.Book;
import com.khoa.play.jooq.tables.BookStore;
import com.khoa.play.jooq.tables.BookToBookStore;
import com.khoa.play.jooq.tables.Language;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Library extends SchemaImpl {

    private static final long serialVersionUID = -864291148;

    /**
     * The reference instance of <code>library</code>
     */
    public static final Library LIBRARY = new Library();

    /**
     * The table <code>library.author</code>.
     */
    public final Author AUTHOR = com.khoa.play.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>library.book</code>.
     */
    public final Book BOOK = com.khoa.play.jooq.tables.Book.BOOK;

    /**
     * The table <code>library.book_store</code>.
     */
    public final BookStore BOOK_STORE = com.khoa.play.jooq.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>library.book_to_book_store</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = com.khoa.play.jooq.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>library.language</code>.
     */
    public final Language LANGUAGE = com.khoa.play.jooq.tables.Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private Library() {
        super("library", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            Language.LANGUAGE);
    }
}
