/*
 * This file is generated by jOOQ.
 */
package com.khoa.play.jooq;


import com.khoa.play.jooq.tables.Author;
import com.khoa.play.jooq.tables.Book;
import com.khoa.play.jooq.tables.BookStore;
import com.khoa.play.jooq.tables.BookToBookStore;
import com.khoa.play.jooq.tables.Language;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = com.khoa.play.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>library.book</code>.
     */
    public static final Book BOOK = com.khoa.play.jooq.tables.Book.BOOK;

    /**
     * The table <code>library.book_store</code>.
     */
    public static final BookStore BOOK_STORE = com.khoa.play.jooq.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>library.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = com.khoa.play.jooq.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>library.language</code>.
     */
    public static final Language LANGUAGE = com.khoa.play.jooq.tables.Language.LANGUAGE;
}
