/*
 * This file is generated by jOOQ.
 */
package com.khoa.play.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language implements Serializable {

    private static final long serialVersionUID = -1391417037;

    private final Long   id;
    private final String cd;
    private final String description;

    public Language(Language value) {
        this.id = value.id;
        this.cd = value.cd;
        this.description = value.description;
    }

    public Language(
        Long   id,
        String cd,
        String description
    ) {
        this.id = id;
        this.cd = cd;
        this.description = description;
    }

    public Long getId() {
        return this.id;
    }

    public String getCd() {
        return this.cd;
    }

    public String getDescription() {
        return this.description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Language (");

        sb.append(id);
        sb.append(", ").append(cd);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
