/*
 * This file is generated by jOOQ.
 */
package com.khoa.play.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1219044763;

    private final Long   id;
    private final String email;
    private final String password;
    private final String status;

    public User(User value) {
        this.id = value.id;
        this.email = value.email;
        this.password = value.password;
        this.status = value.status;
    }

    public User(
        Long   id,
        String email,
        String password,
        String status
    ) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.status = status;
    }

    public Long getId() {
        return this.id;
    }

    public String getEmail() {
        return this.email;
    }

    public String getPassword() {
        return this.password;
    }

    public String getStatus() {
        return this.status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
